### ISSUE TITLE
pvr.plugin.player

### ISSUE THREAD

**Issue by unlocKing** [back-to/repository.back-to#1]
I installed your repo yesterday for the Streamlink plug, but it also installed pvr.plugin.player

Today I noticed the following errors in my log upon each restart:

10:12:07 T:3576   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: attribute of type 'NoneType' is not callable
                                            Traceback (most recent call last):
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.pvr.plugin.player\service.py", line 12, in <module>
                                                throwaway = datetime.datetime.strptime('20110101','%Y%m%d')
                                            TypeError: attribute of type 'NoneType' is not callable
                                            -->End of Python script error report<--

Initially I asked @Primaeval about it, but it turns out it's to do with you as your version has overwrote his.

You should have at least renamed your modified version so he in not inconvenienced with support issues regarding this.

This error is on Windows and Android running Jarvis.

**Comment by back-to** [comment]
I did not change anything in **service.py**

https://github.com/primaeval/plugin.video.pvr.plugin.player/compare/9850d62504affbbeb100019da83e4f6e09edaf4f...back-to:e02864ae70f691cfe07f60b3dff6b194d4ae83e7

in the current version
- i just added a `.gitignore` because there was none when i forked it,
- new icon
- not listed under video addons
- added README

just some small custom changes that i prefer, you would get the same errors with the normal version.

But yeah I will rename this addon, so you can run the normal version of this plugin
and I will delete everything unused in my fork, since i only use it as a proxy right now.

**Comment by back-to** [comment]
Plugin is now renamed and optional, you can now pick the original version if you want.

But you should delete my old version before since its **1.** version

**Comment by unlocKing** [comment]
Thanks dude
